apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
spec:
  type: NodePort
  selector:
    app: shopping-app
  ports:
    - port: 8181         # Service port
      targetPort: 8181   # Container port
      nodePort: 30036    # Exposed NodePort
