apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
        - name: shopping-app-container
          image: khadar3099/shopping:v.3
          ports:
            - containerPort: 8181
